name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install logrotate
      run: sudo apt-get install logrotate

    - name: Mode test
      run: pwd

    - name: Mode test
      run: ls -al /var/log

    - name: Mode test
      run: chmod 755 test.sh
  
    - name: List Logrotate
      run: ./test.sh
