name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check /proc/mounts
      run: cat /proc/mounts

    - name: Check FileSystem
      run: df -h

    - name: Check pvdisplay
      run: sudo pvs

    - name: Check vgdisplay
      run: sudo vgs
    
    - name: Check lvsdisplay
      run: sudo lvs

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
