name: PHP Composer

on: 
  workflow_dispatch:
    inputs:
      source:
        description: 'Source Github'     
        required: true
        default: 'https://github.com/lepetitadmin/Test-CI'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout test repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.inputs.source }}
        path: main

    - name: Install logrotate
      run: sudo apt-get install logrotate

    - name: Mode test
      run: chmod 755 test.sh
  
    - name: List Logrotate
      run: ./test.sh
